import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "./SessionProviderWrapper";
import Header from "@/_components/common/Header";
import { AlertProvider } from "@/_context/AlertProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
          <main
            id="main-wrapper"
            className="w-full max-w-[460px] max-h-[100vh] relative overflow-hidden overflow-y-auto
            mx-auto bg-[#fdf2e3] border-l-1 border-r-1 border-[#dfdfdf]"
          >
            <AlertProvider>
              <Header />
              {children}
            </AlertProvider>
          </main>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
